name: Build Docker Image on main branch

on:
    push:
        branches:
            - 'main'

jobs:
    docker_build_and_publish_github:
        runs-on: self-hosted
        steps:
            -   name: Check out the repo
                uses: actions/checkout@v3

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v2

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2

            -   name: Login to GitHub Container Registry
                uses: docker/login-action@v2
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Docker meta
                id: meta
                uses: docker/metadata-action@v4
                with:
                    images: |
                        ghcr.io/stefan-lange/${{ github.repository }}
                    tags: |
                        type=raw,value=latest
                        type=raw,value=main

            -   name: Build docker image and push to github packages
                uses: docker/build-push-action@v3
                with:
                    context: .
                    platforms: linux/amd64,linux/arm64
                    no-cache: true
                    push: true
                    build-args: |
                        "BRANCH=main"
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
