name: Build Binaries

on:
    push:
        branches:
            - main
        tags:
            - '**'
    pull_request:

jobs:
    build:
        runs-on: self-hosted
        container: golang:1
        strategy:
            matrix:
                GOOS: [ "linux", "darwin", "windows" ]
                GOARCH: [ "amd64", "arm64" ]
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Build Binary
                env:
                    GOOS: ${{ matrix.GOOS }}
                    GOARCH: ${{ matrix.GOARCH }}
                run: make build

            -   name: Upload artifacts
                uses: actions/upload-artifact@v3
                with:
                    name: chia-price-exporter-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
                    path: ${{ github.workspace }}/bin/chia-price-exporter*

    release:
        runs-on: self-hosted
        needs:
            - build
        if: startsWith(github.ref, 'refs/tags/')
        steps:
            -   uses: actions/checkout@v3

            -   uses: actions/download-artifact@v3
                with:
                    path: artifacts

            -   name: Show artifacts
                run: tree artifacts

            -   name: Generate artifact zips
                run: |
                    cd ${{ github.workspace }}/artifacts || exit 1
                    DIRS=$(find . -type d -name 'chia-price-exporter*')
                    while IFS= read -r dir; do
                      echo "Creating zip for $dir..."
                      zip -r $dir.zip $dir
                    done <<< "$DIRS"

            -   name: Get tag name
                if: startsWith(github.ref, 'refs/tags/')
                id: tag-name
                run: |
                    TAG_NAME=$(echo ${{ github.ref }} | cut -d'/' -f 3)
                    echo "TAG_NAME=$TAG_NAME" >>$GITHUB_ENV
                    echo "TAG_NAME=$TAG_NAME" >>$GITHUB_OUTPUT

            -   name: Upload Release Artifacts
                env:
                    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: |
                    FILES=$(find ${{ github.workspace }}/artifacts -type f -name 'chia-price-exporter*.zip')
                    while IFS= read -r file; do
                      gh release upload \
                        $TAG_NAME \
                        $file
                    done <<< "$FILES"

